In [1]:
import numpy as np
import pandas as pd

In [8]:
A = np.array([[2,2,1],[2,6,3],[2,3,-5]])
B = np.array([[3,1,2],[-1,2,4],[2,6,3]])
print(A, end="\n \n")
print(B)

[[ 2  2  1]
 [ 2  6  3]
 [ 2  3 -5]]
 
[[ 3  1  2]
 [-1  2  4]
 [ 2  6  3]]


In [13]:
print("Rank of B^2:", np.linalg.matrix_rank(np.linalg.matrix_power(B, 2)))

Rank of B^2 is 3


In [15]:
print("3A - 4B:", 3*A - 4*B, sep = "\n")

3A - 4B:
[[ -6   2  -5]
 [ 10  10  -7]
 [ -2 -15 -27]]


In [16]:
print("Main diagonal sum (trace) of A + B:", np.trace(A + B))

Main diagonal sum of A + B: 11


In [20]:
print("Test for (A+B)^T = A^T + B^T:", (np.transpose(A+B) == np.transpose(A) + np.transpose(B)).all())

Test for (A+B)^T = A^T + B^T: True



In [23]:
print("Test for AB = BA:", (A@B == B@A).all())

Test for AB = BA: False


In [30]:
print("Test for (AB)^-1 = (B^-1)(A^-1):", (np.linalg.inv(A@B) == np.linalg.inv(A) @ np.linalg.inv(B)).all())

Test for (AB)^-1 = (B^-1)(A^-1): False


In [29]:
print("Test for det(AB) = det(A) * det(B): ", (np.linalg.det(A@B) == np.linalg.det(A) * np.linalg.det(B)).all())

Test for det(AB) = det(A) * det(B):  True


In [50]:
b_transpose = np.array([1,-2,-3]).reshape(1,3)
b = np.transpose(b_transpose)
print("b is: ", b, sep="\n", end="\n\n")
print("Find x for Ax = Bb <=> x = A^-1(Bb):", np.linalg.inv(A) @ B @ b, sep = "\n")

b is: 
[[ 1]
 [-2]
 [-3]]

Find x for Ax = Bb <=> x = A^-1(Bb):
[[ 0.5       ]
 [-3.84615385]
 [ 1.69230769]]


In [56]:
print("Test for Ax = bB:")
try:
    print("Try b@B")
    print(b@B)
except ValueError:
    print("b and B don't have the correct sizes")
    print("b shape", b.shape)
    print("B shape", B.shape)

Test for Ax = bB:
Try b@B
b and B don't have the correct sizes
b shape (3, 1)
B shape (3, 3)


In [59]:
C = np.random.randint(-6, 6, [3,3])
print("C value:", C, sep="\n")

C value:
[[-1 -4  5]
 [-2 -6 -3]
 [-4  0 -1]]


In [61]:
print("Test (AB)C = A(BC):", ((A@B)@C == A@(B@C)).all())

Test (AB)C = A(BC): True
