In [1]:
import numpy as np
import pandas as pd

In [5]:
data = [6,7,8,9,10]
print(data)

[6, 7, 8, 9, 10]


In [7]:
arr = np.array(data)
print(arr)

[ 6  7  8  9 10]


In [9]:
arr = np.array([[2,3,4],[4,5,6]])
print(arr)

[[2 3 4]
 [4 5 6]]


In [10]:
arr.ndim

2

In [11]:
arr.dtype

dtype('int32')

In [12]:
arr.shape

(2, 3)

In [16]:
np.arange(4, 6)

array([4, 5])

In [18]:
arr.max()

6

In [19]:
arr.min()

2

In [21]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [23]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [24]:
arr = np.arange(8)

In [25]:
arr[1:6]

array([1, 2, 3, 4, 5])

**Libraries: numpy, scipy, sympy

In [26]:
arr1 = [1., 2.]
arr2 = [3., 4.]

In [27]:
2 * arr1

[1.0, 2.0, 1.0, 2.0]

In [28]:
arr1 * 2

[1.0, 2.0, 1.0, 2.0]

In [52]:
ranks = [1,2,3,4]
scores = [9,8,7,6]
names = ["h","z","q","s"]
res = zip(ranks, scores, names)
res

In [48]:
# res = set(res)
# res

{(1, 9, 'h'), (2, 8, 'z'), (3, 7, 'q'), (4, 6, 's')}

In [53]:
r, s, n = zip(*res)
r

(1, 2, 3, 4)

In [54]:
n

('h', 'z', 'q', 's')

In [55]:
2**3

8

In [56]:
import math

In [57]:
pow(2,3)

8

In [59]:
math.pi

3.141592653589793

In [62]:
math.gcd(10, -18)

2

In [63]:
sum(arr)

28

In [64]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [65]:
math.fsum(arr)

28.0

In [66]:
arr = np.array([1,2,3])

In [67]:
arr

array([1, 2, 3])

In [68]:
arr * arr

array([1, 4, 9])

In [70]:
arr @ arr.T

14

In [71]:
arr = np.array([1,"H"])

In [72]:
arr

array(['1', 'H'], dtype='<U11')

In [79]:
np.random.seed(69)
np.random.randint(5, 10, (3,4))

array([[8, 6, 8, 7],
       [9, 6, 6, 5],
       [6, 5, 5, 9]])

In [80]:
a = np.array([4,6,7,2,3])
b = a[:-1]
a

array([4, 6, 7, 2, 3])

In [81]:
b

array([4, 6, 7, 2])

In [87]:
a = np.array([3,27])
a

array([ 3, 27])

In [88]:
np.linalg.norm(a, np.inf)

27.0

In [91]:
a = np.arange(1,3)
b = np.arange(6,8)
np.vstack([a,b])

array([[1, 2],
       [6, 7]])

In [92]:
np.hstack([a,b])

array([1, 2, 6, 7])

In [93]:
v = np.array([2,3])
m1 = np.array([[1,2],[3,4]])
v @ m1

array([11, 16])

In [94]:
m1 @ v

array([ 8, 18])

In [99]:
a = np.random.randint(0, 11, 9).reshape(3,3)
a

array([[2, 1, 2],
       [5, 8, 0],
       [9, 2, 1]])

In [100]:
b = np.random.randint(0, 11, 9).reshape(3,3)
b

array([[3, 7, 5],
       [0, 0, 1],
       [0, 8, 9]])

In [109]:
a_norm_1 = np.linalg.norm(a[0], 2)
a_norm_3 = np.linalg.norm(a[2], 2)
print(a_norm_1)
print(a_norm_3)

3.0
9.273618495495704


In [111]:
b_norm_1 = np.linalg.norm(b[0], 2)
b_norm_3 = np.linalg.norm(b[2], 2)
print(b_norm_1)
print(b_norm_3)

9.1104335791443
12.041594578792296


In [112]:
a + b

array([[ 5,  8,  7],
       [ 5,  8,  1],
       [ 9, 10, 10]])

In [113]:
a - b

array([[-1, -6, -3],
       [ 5,  8, -1],
       [ 9, -6, -8]])

In [114]:
a @ b

array([[ 6, 30, 29],
       [15, 35, 33],
       [27, 71, 56]])

In [115]:
a = 0
b = 100

In [118]:
arr = np.arange(a, b, 21)
arr

array([ 0, 21, 42, 63, 84])

In [123]:
a = np.linspace(0, 100, 21)

In [124]:
a,b,c = np.split(a, 3)

In [125]:
a*b

array([   0.,  200.,  450.,  750., 1100., 1500., 1950.])

In [126]:
a.dot(b)

5950.0

In [146]:
A = np.array([[1, 0, 2, 1],[1,2,4,2],[-1,2,0,3],[3,-1,3,4]])
B = np.array([[4,5,1,-2],[0,1,2,1],[0,-2,-3,1],[1,2,3,4]])
B + A

array([[ 5,  5,  3, -1],
       [ 1,  3,  6,  3],
       [-1,  0, -3,  4],
       [ 4,  1,  6,  8]])

In [133]:
B * A.T

array([[ 4,  5, -1, -6],
       [ 0,  2,  4, -1],
       [ 0, -8,  0,  3],
       [ 1,  4,  9, 16]])

In [134]:
2 * A - 3 * B

array([[-10, -15,   1,   8],
       [  2,   1,   2,   1],
       [ -2,  10,   9,   3],
       [  3,  -8,  -3,  -4]])

In [135]:
np.linalg.det(A)

12.000000000000005

In [136]:
np.linalg.det(B.T + 2 * np.identity(4))

-26.000000000000004

In [137]:
np.linalg.matrix_rank(A@B)

3

In [164]:
a = A[0, :]
np.linalg.norm(a, 1)

4.0

In [166]:
b = A[:, 2]
np.linalg.norm(b, 1)

9.0

In [141]:
np.diagonal(A).sum()

7

In [168]:
np.all((A@B).T==B.T@A.T)

True

In [169]:
C=np.random.randint(-9,9,16).reshape(4,4)
np.tril(A+B@C)

array([[ 17,   0,   0,   0],
       [-17,   0,   0,   0],
       [ 21, -15, -38,   0],
       [-24, -26,  16,   7]])

In [171]:
np.linalg.inv(A-np.identity(4))@B

array([[-3.91891892, -4.24324324,  0.48648649,  3.08108108],
       [-4.08108108, -4.75675676, -0.48648649,  1.91891892],
       [ 1.10810811,  1.67567568,  0.64864865, -0.89189189],
       [ 1.78378378,  1.64864865, -0.2972973 , -0.21621622]])

In [ ]:
# 2 dãy un - vn u1 = 1; v1 = 2; u n+1 = 2un + 2vn
# vn+! =  